### PR TITLE
Search bar done

### LINKED ISSUE #12: Search for posts
**Description**:  
Ability to search for posts

**Acceptance Tasks**:  
[Game based search](https://github.com/itslupus/gamersnet/issues/13)
[Search filter](https://github.com/itslupus/gamersnet/issues/14)

**Story Points (1 - 5**): 4

### LINKED ISSUE #13: Game based search
**Description**:  
As a user, I want to be able to search for posts to find players that are playing my game

**Acceptance Criteria**:  
Users can Search posts by name of games from the search bar on the header

**Dev Tasks**: 
[Backend endpoint to fetch posts](https://github.com/itslupus/gamersnet/issues/15)(4hrs)
[Frontend UI to select games](https://github.com/itslupus/gamersnet/issues/16)
[Frontend UI to display posts by games](https://github.com/itslupus/gamersnet/issues/17)

**Story Points (1 - 5**): 3

### LINKED ISSUE #17: Create frontend UI to display posts by specific games
**Description**:  
Create frontend UI to display posts by specific games

### LINKED ISSUE #91: Home page lists all posts instead of valid/unexpired posts
**Description**:  
Didn't test it but saw the post display on homepage using the wrong API call, listAllPosts instead of listValidPosts. Need to recheck it and change if required.

### PR DESCRIPTION
**Pull request by Azarov204**
#14 #16 #17

### CODE REVIEW

**Comment by lucashuy** [comment]
PR #89 should be merged before this one

**Comment by lucashuy** [comment]
This PR resolves #91

**Review by lucashuy — APPROVED** [review]
The parts that I did not write look good to me

**Review by humayraR — APPROVED** [review]

**Review by humayraR — APPROVED** [review]
Looks good enough to be merged.

**Review by jayKhakhariya — APPROVED** [review]

**Pull request merged**
