### PR TITLE
Rating frontend

### LINKED ISSUE #8: Rate a user
**Description**:  
Ability to rate a user for a specific game based on the skills encountered while playing games.

**User Stories**:  
[Rate players](https://github.com/itslupus/gamersnet/issues/25)
[Comment on players profile](https://github.com/itslupus/gamersnet/issues/26)
[Edit Rating](https://github.com/itslupus/gamersnet/issues/95)

### LINKED ISSUE #25: Rate players
**Description**:  
As a user, I want to be able to rate the players I played with based on kindness, punctuality, how accurate their suggested skill level is, etc.

**Acceptance Criteria**:  
* Users should not be able to rate other users from my account
* users can go to another user profile and add their rating
* they can view the average ratings on user profiles

**Dev Tasks**:  
[Create front-end to select a player](https://github.com/itslupus/gamersnet/issues/27)
[Create a front-end to rate the player once he/she is selected](https://github.com/itslupus/gamersnet/issues/28)
[Create a backend POST to rate a player](https://github.com/itslupus/gamersnet/issues/29) (4.5hrs)

**Story Points (1 - 5**): 3

### LINKED ISSUE #26: Comment on players profile
**Description**:  
As a user, I want to be able to comment on profiles

**Acceptance Criteria**:  
* Users should only be able to comment on other profiles from their account.
* Users should only be able to comment on existing users' profiles.
* Users should only be able to comment if they are logged in.

**Dev Tasks**:  
[Create front-end UI for commenting](https://github.com/itslupus/gamersnet/issues/30)
[Create backend endpoint to create comment](https://github.com/itslupus/gamersnet/issues/31)(0.5hr)

**Story Points (1 - 5**): 2

### LINKED ISSUE #27: Create front-end to select a player
**Description**:  
Create front-end to select a player

### LINKED ISSUE #28: Create a front-end to rate the player once he/she is selected
**Description**:  
Create a front-end to rate the player once he/she is selected

### LINKED ISSUE #30: Create front-end UI for commenting on user's profile
**Description**:  
Create front-end UI for commenting on user's profile

### LINKED ISSUE #78: Code smell regarding getUserIDFromToken()
https://github.com/itslupus/gamersnet/blob/ece5e27df24e634c67815d434640d03b45153a44/gamersnet_backend/persistence/tokens.js#L52
Not quite a bug, more so a code smell. This function doesn't actually get the `userID` from token, it gets the entire token document. This should be fixed before Sprint 4 (though that probably falls into my hands since I wrote that function).

### LINKED ISSUE #94: Edit user rating frontend
**Description**:  
Handle users trying to rerate profile. 
UI for edit rating.

### LINKED ISSUE #95: Edit Rating
**Description**:  
One can rate a user profile only one time, not more than that. But can edit their ratings if they want.

**Acceptance Criteria**:  
* User goes to a user profile that he/she already rated once.\
* When user goes to another profile, he can see his rating as "your rating"  on the user's profile.
* can't multiple ratings
* can edit the previously added rating

**Dev Tasks**:  
[Edit rating profile backend](https://github.com/itslupus/gamersnet/issues/93) (1.5hr)
[Edit rating profile frontend](https://github.com/itslupus/gamersnet/issues/94)

**Story Points (1 - 5**): 2

### PR DESCRIPTION
**Pull request by lucashuy**
This PR address the following:
- Closes #78 
- Closes #30 
- Closes #26
- Closes #27 
- Closes #28 
- Closes #25
- Closes #94
- Closes #95
- Closes #8

This PR will finish the user rating and comment related user stories.

### CODE REVIEW

**Comment by lucashuy** [comment]
The profile component does not re-render after a URL change. Looking into fix

**Comment by lucashuy** [comment]
Ready for review

**Review by humayraR — DISMISSED** [review]
code looks good other than the fact that i couldn't test adding/editing rating on a profile. Can be merged in case other branches need changes from this PR

**Review by humayraR — APPROVED** [review]
Look great and works as expected!

**Pull request merged**
